apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    name: hive
  name: hive
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: hive:latest
  postCommit: {}
  resources:
    requests:
      cpu: "4"
      memory: 2Gi
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/openshift/hive.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: "<CHANGE-ME>"
    type: GitHub
  - type: ConfigChange
