apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hiveapi-hive-hiveapi
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:openshift:hive:hiveapi
subjects:
  - kind: ServiceAccount
    namespace: hive
    name: hiveapi-sa
